select
    nu_ano, 
    nu_inscricao, 
    tp_faixa_etaria, 
    tp_sexo, 
    tp_estado_civil, 
    tp_cor_raca, 
    tp_nacionalidade, 
    tp_st_conclusao, 
    tp_ano_concluiu, 
    tp_escola, 
    tp_ensino, 
    in_treineiro, 
    co_municipio_esc, 
    no_municipio_esc, 
    co_uf_esc, 
    sg_uf_esc, 
    tp_dependencia_adm_esc, 
    tp_localizacao_esc, 
    tp_sit_func_esc, 
    co_municipio_prova, 
    no_municipio_prova, 
    co_uf_prova, 
    sg_uf_prova, 
    tp_presenca_cn, 
    tp_presenca_ch, 
    tp_presenca_lc, 
    tp_presenca_mt, 
    co_prova_cn, 
    co_prova_ch, 
    co_prova_lc, 
    co_prova_mt, 
    nu_nota_cn, 
    nu_nota_ch, 
    nu_nota_lc, 
    nu_nota_mt, 
    tx_respostas_cn, 
    tx_respostas_ch, 
    tx_respostas_lc, 
    tx_respostas_mt, 
    tp_lingua, 
    tx_gabarito_cn, 
    tx_gabarito_ch, 
    tx_gabarito_lc, 
    tx_gabarito_mt, 
    tp_status_redacao, 
    nu_nota_comp1, 
    nu_nota_comp2, 
    nu_nota_comp3, 
    nu_nota_comp4, 
    nu_nota_comp5, 
    nu_nota_redacao, 
    q001 as educacao_pai, 
    q002 as educacao_mae, 
    q003 as ocupacao_pai, 
    q004 as ocupacao_mae, 
    q005 as num_pessoas_residencia, 
    q006 as renda_familia, 
    q007 as empregado_domestico, 
    q008 as residencia_banheiros, 
    q009 as residencia_quartos, 
    q010 as residencia_carros, 
    q011 as residencia_motocicleta, 
    q012 as residencia_geladeira, 
    q013 as residencia_freezer, 
    q014 as residencia_maquina_lava_roupa, 
    q015 as residencia_maquina_seca_roupa, 
    q016 as residencia_microondas,
    q017 as residencia_lava_louca, 
    q018 as residencia_aspirador_po, 
    q019 as residencia_tv_cores, 
    q020 as residencia_dvd, 
    q021 as residencia_tv_assinatura, 
    q022 as residencia_tel_celular, 
    q023 as residencia_tel_fixo, 
    q024 as residencia_computador, 
    q025 as residencia_internet
from 
    {{ source('enem', '2023') }}